Fix timeout of model runner test
Model runner test failed due to timeout intermittently.
We can increase default timeout from 5s to 20s to make it stable.

```
Chrome 60.0.3112 (Mac OS X 10.12.6) Model runner basic train usage, train 3 batches FAILED
	Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
```